trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  stage:
    steps:
    - script: dotnet build --configuration $(buildconfiguration)
      displaytime: 'dotnet build $(buildconfiguration)'
    - script: dotnet test
      displayname: 'dotnet test'  
 


